---
dbscripts:
  portal:
    up: portal_schema.sql
    down: portal_drop_schema.sql
  audit:
    up: audit_schema.sql
    down: audit_drop_schema.sql
  config:
    up: content_schema.sql
    down: content_drop_schema.sql
  content:
    up: content_schema.sql
    down: content_drop_schema.sql
  resource:
    up: content_schema.sql
    down: content_drop_schema.sql
  orchestr:
    up: orchestrator_schema.sql
    down: orchestrator_drop_schema.sql
  tracking:
    up: tracking_schema.sql
    down: tracking_drop_schema.sql